''' SQL

DROP DATABASE IF EXISTS ecommerce ;

CREATE DATABASE ecommerce;

USE ecommerce;

CREATE TABLE CLIENTE (
    IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(70) DEFAULT 'SIN_REGISTRO',
    DNI VARCHAR (15) NOT NULL,
    TELEFONO VARCHAR(15) NOT NULL,
    CORREO VARCHAR (100) UNIQUE NOT NULL,
    DIRECCION_DE_ENTREGA VARCHAR (100) NOT NULL
);

CREATE TABLE PRODUCTOS (
IDPRODUCTO INT PRIMARY KEY AUTO_INCREMENT,
    MODELO VARCHAR(100) DEFAULT 'SIN_REGISTRO',
    STOCK VARCHAR(100) DEFAULT 'SIN_STOCK',
    PRECIO INT
);

CREATE TABLE TIPOPEDIDORESERVA (
    IDTIPOPEDIDORESERVA INT PRIMARY KEY AUTO_INCREMENT,
    TIPO VARCHAR(50)
);

CREATE TABLE RETIROTAKEAWAY (
    IDSUCURSAL INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    DIRECCION VARCHAR(150),
    TELEFONO VARCHAR(25)
);

CREATE TABLE PEDIDOS (
IDPEDIDORESERVA INT PRIMARY KEY AUTO_INCREMENT,
    IDCLIENTE INT,
    IDPRODUCTO INT,
    IDTIPOPEDIDORESERVA INT,
    IDSUCURSAL INT,
    FECHA DATETIME,
    CANCELACION_PEDIDO DATETIME DEFAULT NULL
);

-- TABLA PARA HISTORIAL DE STOCK

CREATE TABLE HISTORIAL_STOCK (
    IDHISTORIAL_STOCK INT PRIMARY KEY AUTO_INCREMENT,
    IDPRODUCTO INT,
    CAMBIO INT,
    FECHA DATETIME,
    RAZON VARCHAR(255),
    FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTOS(IDPRODUCTO)
);

-- TABLA PARA LAS DIRECCIONES DE FACTURACION.

CREATE TABLE DIRECCIONES_FACTURACION (
    IDDIRECCION_FACTURACION INT PRIMARY KEY AUTO_INCREMENT,
    IDCLIENTE INT,
    DIRECCION VARCHAR(100),
    FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);

-- TABLA DE RESEÑAS.

CREATE TABLE RESENAS (
    IDRESENA INT PRIMARY KEY AUTO_INCREMENT,
    IDPRODUCTO INT,
    IDCLIENTE INT,
    CALIFICACION INT CHECK (CALIFICACION BETWEEN 1 AND 5),
    COMENTARIO TEXT,
    FECHA DATETIME,
    FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTOS(IDPRODUCTO),
    FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);


-- FOREIGN KEYS


ALTER TABLE PEDIDOS
    ADD CONSTRAINT FK_PEDIDO_RESERVA_CLIENTE
    FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE);

ALTER TABLE PEDIDOS
    ADD CONSTRAINT FK_PEDIDO_PRODUCTO
    FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTOS(IDPRODUCTO);

ALTER TABLE PEDIDOS
    ADD CONSTRAINT FK_TAKE_AWAY
    FOREIGN KEY (IDSUCURSAL) REFERENCES RETIROTAKEAWAY(IDSUCURSAL);
    
ALTER TABLE PEDIDOS
    ADD CONSTRAINT FK_PEDIDO_RESERVA
    FOREIGN KEY (IDTIPOPEDIDORESERVA) REFERENCES TIPOPEDIDORESERVA(IDTIPOPEDIDORESERVA);
