''' SQL

DROP DATABASE IF EXISTS ecommerce ;

CREATE DATABASE ecommerce;

USE ecommerce;

CREATE TABLE CLIENTE (
    IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(70) DEFAULT 'SIN_REGISTRO',
    DNI VARCHAR (15) NOT NULL,
    TELEFONO VARCHAR(15) NOT NULL,
    CORREO VARCHAR (100) UNIQUE NOT NULL,
    DIRECCION_DE_ENTREGA VARCHAR (100) NOT NULL
);

CREATE TABLE PRODUCTOS (
IDPRODUCTO INT PRIMARY KEY AUTO_INCREMENT,
    MODELO VARCHAR(100) DEFAULT 'SIN_REGISTRO',
    STOCK VARCHAR(100) DEFAULT 'SIN_STOCK',
    PRECIO INT
);

CREATE TABLE TIPOPEDIDORESERVA (
    IDTIPOPEDIDORESERVA INT PRIMARY KEY AUTO_INCREMENT,
    TIPO VARCHAR(50)
);

CREATE TABLE RETIROTAKEAWAY (
    IDSUCURSAL INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    DIRECCION VARCHAR(150),
    TELEFONO VARCHAR(25)
);

CREATE TABLE PEDIDOS (
IDPEDIDORESERVA INT PRIMARY KEY AUTO_INCREMENT,
    IDCLIENTE INT,
    IDPRODUCTO INT,
    IDTIPOPEDIDORESERVA INT,
    FECHA DATETIME,
    CANCELACION_PEDIDO DATETIME DEFAULT NULL
);


-- FOREIGN KEYS


ALTER TABLE PEDIDOS
    ADD CONSTRAINT FK_PEDIDO_RESERVA_CLIENTE
    FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE);

ALTER TABLE PEDIDOS
    ADD CONSTRAINT FK_PEDIDO_PRODUCTO
    FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTOS(IDPRODUCTO);

ALTER TABLE PEDIDOS
    ADD CONSTRAINT FK_TAKE_AWAY
    FOREIGN KEY (IDSUCURSAL) REFERENCES RETIROTAKEAWAY(IDSUCURSAL);
    
ALTER TABLE PEDIDOS
    ADD CONSTRAINT FK_PEDIDO_RESERVA
    FOREIGN KEY (IDTIPOPEDIDORESERVA) REFERENCES TIPOPEDIDORESERVA(IDTIPOPEDIDORESERVA);
